export const events = [
  {
    title: "React Summit 2026",
    image: "/images/event1.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "October 8-10, 2026",
    time: "9:00 AM",
  },
  {
    title: "KubeCon + CloudNativeCon Europe",
    image: "/images/event2.png",
    slug: "kubecon-cloudnativecon-europe",
    location: "London, United Kingdom",
    date: "March 16-19, 2026",
    time: "8:30 AM",
  },
  {
    title: "Google I/O Extended 2026",
    image: "/images/event3.png",
    slug: "google-io-extended-2026",
    location: "San Francisco, USA",
    date: "May 20, 2026",
    time: "10:00 AM",
  },
  {
    title: "Hacktoberfest Meetup Night",
    image: "/images/event4.png",
    slug: "hacktoberfest-meetup-night",
    location: "Toronto, Canada",
    date: "October 25, 2026",
    time: "6:30 PM",
  },
  {
    title: "DevOpsDays Seattle",
    image: "/images/event5.png",
    slug: "devopsdays-seattle",
    location: "Seattle, USA",
    date: "June 3-4, 2026",
    time: "9:00 AM",
  },
  {
    title: "Tech Meetup: AI & Product Design",
    image: "/images/event6.png",
    slug: "ai-product-design-meetup",
    location: "Berlin, Germany",
    date: "August 14, 2026",
    time: "7:00 PM",
  },
];
